script: "bundle exec rake"
bundler_args: --without perf
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-head
  - jruby-18mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
