language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev

script: "bundle exec rake"

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ree

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ree
